name: tqdm
description: A Dart progress bar package inspired by Python's tqdm.
version: 1.0.2
repository: https://github.com/fa0311/tqdm_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
